"""add new tables

Revision ID: 00418a0286f0
Revises: 1bf7a177a6a2
Create Date: 2025-01-09 06:33:24.200672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '00418a0286f0'
down_revision: Union[str, None] = '1bf7a177a6a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_payments_order_id', 'payments', ['order_id'])
    op.create_table('box_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=100), nullable=False),
    sa.Column('type_box', sa.Enum('SMALL_BOX', 'MEDIUM_BOX', 'LARGE_BOX', name='typebox'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['payments.order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_box_payment_id'), 'box_payment', ['id'], unique=False)
    op.create_table('energy_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=100), nullable=False),
    sa.Column('amount_energy', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['payments.order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energy_payment_id'), 'energy_payment', ['id'], unique=False)
    op.create_table('money_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=100), nullable=False),
    sa.Column('count_money', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['payments.order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_money_payment_id'), 'money_payment', ['id'], unique=False)
    op.create_table('vip_pass_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=100), nullable=False),
    sa.Column('type_vip_pass', sa.Enum('seven_days_pass', 'month_pass', name='typesvippass'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['payments.order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vip_pass_payment_id'), 'vip_pass_payment', ['id'], unique=False)
    op.add_column('characters', sa.Column('vip_pass_expiration_date', sa.DateTime(), nullable=True))
    op.drop_column('payments', 'amount_energy')
    op.drop_column('payments', 'type_box')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_box_payment_order_id', 'box_payment', type_='foreignkey')
    op.drop_constraint('fk_energy_payment_order_id', 'energy_payment', type_='foreignkey')
    op.drop_constraint('fk_money_payment_order_id', 'money_payment', type_='foreignkey')
    op.drop_constraint('fk_vip_pass_payment_order_id', 'vip_pass_payment', type_='foreignkey')

    # ### Удаление уникального ограничения ###
    op.drop_constraint('uq_payments_order_id', 'payments', type_='unique')

    # ### Добавление индексов заново ###
    op.create_foreign_key(
        'fk_box_payment_order_id',
        'box_payment',
        'payments',
        ['order_id'],
        ['order_id'],
        ondelete='CASCADE'
    )
    op.create_foreign_key(
        'fk_energy_payment_order_id',
        'energy_payment',
        'payments',
        ['order_id'],
        ['order_id'],
        ondelete='CASCADE'
    )
    op.create_foreign_key(
        'fk_money_payment_order_id',
        'money_payment',
        'payments',
        ['order_id'],
        ['order_id'],
        ondelete='CASCADE'
    )
    op.create_foreign_key(
        'fk_vip_pass_payment_order_id',
        'vip_pass_payment',
        'payments',
        ['order_id'],
        ['order_id'],
        ondelete='CASCADE'
    )

    # Остальной downgrade-код
    op.add_column('payments', sa.Column('type_box', mysql.ENUM('SMALL_BOX', 'MEDIUM_BOX', 'LARGE_BOX'), nullable=True))
    op.add_column('payments', sa.Column('amount_energy', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('characters', 'vip_pass_expiration_date')
    op.drop_index(op.f('ix_vip_pass_payment_id'), table_name='vip_pass_payment')
    op.drop_table('vip_pass_payment')
    op.drop_index(op.f('ix_money_payment_id'), table_name='money_payment')
    op.drop_table('money_payment')
    op.drop_index(op.f('ix_energy_payment_id'), table_name='energy_payment')
    op.drop_table('energy_payment')
    op.drop_index(op.f('ix_box_payment_id'), table_name='box_payment')
    op.drop_table('box_payment')
    # ### end Alembic commands ###
