"""add_column_character_in_training

Revision ID: 0b752e3ce01b
Revises: f8fd066f807d
Create Date: 2024-08-13 15:05:33.898465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b752e3ce01b'
down_revision: Union[str, None] = 'f8fd066f807d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('character_in_training', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'character_in_training')
    # ### end Alembic commands ###
