"""add new column Payment

Revision ID: 1bf7a177a6a2
Revises: 73698f613609
Create Date: 2024-12-26 16:46:47.796851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1bf7a177a6a2'
down_revision: Union[str, None] = '73698f613609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('type_box', sa.Enum('SMALL_BOX', 'MEDIUM_BOX', 'LARGE_BOX', name='typebox'), nullable=True))
    op.alter_column('payments', 'amount_energy',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'amount_energy',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('payments', 'type_box')
    # ### end Alembic commands ###
