"""add ner colum to table

Revision ID: 1ca92a4446c8
Revises: 3431d480ff9b
Create Date: 2025-06-26 20:53:33.216319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1ca92a4446c8'
down_revision: Union[str, None] = '3431d480ff9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('is_invite_only', sa.Boolean(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clubs', 'is_invite_only')
    # ### end Alembic commands ###
