"""add new table club_infrastructure

Revision ID: 205648c63b51
Revises: 3f19b8d8bbf0
Create Date: 2025-03-07 17:59:17.336709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '205648c63b51'
down_revision: Union[str, None] = '3f19b8d8bbf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_infrastructures',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('club_id', sa.BigInteger(), nullable=False),
    sa.Column('points', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_update_points', sa.DateTime(), server_default=sa.text("TIMESTAMP '1970-01-01 00:00:00'"), nullable=False),
    sa.Column('training_base', sa.Enum('LEVEL_0', 'LEVEL_1', 'LEVEL_2', 'LEVEL_3', 'LEVEL_4', 'LEVEL_5', name='infrastructurelevel'), server_default=sa.text("'LEVEL_0'"), nullable=False),
    sa.Column('training_center', sa.Enum('LEVEL_0', 'LEVEL_1', 'LEVEL_2', 'LEVEL_3', 'LEVEL_4', 'LEVEL_5', name='infrastructurelevel'), server_default=sa.text("'LEVEL_0'"), nullable=False),
    sa.Column('premium_fond', sa.Enum('LEVEL_0', 'LEVEL_1', 'LEVEL_2', 'LEVEL_3', 'LEVEL_4', 'LEVEL_5', name='infrastructurelevel'), server_default=sa.text("'LEVEL_0'"), nullable=False),
    sa.Column('stadium', sa.Enum('LEVEL_0', 'LEVEL_1', 'LEVEL_2', 'LEVEL_3', 'LEVEL_4', 'LEVEL_5', name='infrastructurelevel'), server_default=sa.text("'LEVEL_0'"), nullable=False),
    sa.Column('sports_medicine', sa.Enum('LEVEL_0', 'LEVEL_1', 'LEVEL_2', 'LEVEL_3', 'LEVEL_4', 'LEVEL_5', name='infrastructurelevel'), server_default=sa.text("'LEVEL_0'"), nullable=False),
    sa.Column('academy_talent', sa.Enum('LEVEL_0', 'LEVEL_1', 'LEVEL_2', 'LEVEL_3', 'LEVEL_4', 'LEVEL_5', name='infrastructurelevel'), server_default=sa.text("'LEVEL_0'"), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_club_infrastructures_id'), 'club_infrastructures', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(op.f('ix_club_infrastructures_id'), table_name='club_infrastructures')
    op.drop_table('club_infrastructures')
    # ### end Alembic commands ###
