"""add_new_table_club

Revision ID: 255aed4ceb1f
Revises: 0b752e3ce01b
Create Date: 2024-08-14 16:08:50.233664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '255aed4ceb1f'
down_revision: Union[str, None] = '0b752e3ce01b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name_club', sa.String(length=100), nullable=False),
    sa.Column('league', sa.String(length=100), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('link_to_chat', sa.String(length=255), nullable=True),
    sa.Column('energy_applied', sa.Integer(), server_default='0', nullable=True),

    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clubs_id'), 'clubs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clubs_id'), table_name='clubs')
    op.drop_table('clubs')
    # ### end Alembic commands ###
