"""add_new_cloum_league

Revision ID: 255cc8c925bf
Revises: 4c0b77640ce6
Create Date: 2024-08-14 20:15:59.605726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '255cc8c925bf'
down_revision: Union[str, None] = '4c0b77640ce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('league', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clubs', 'league')
    # ### end Alembic commands ###
