"""add register_user_colum

Revision ID: 3f19b8d8bbf0
Revises: 613a66bc7de0
Create Date: 2025-03-01 20:36:08.697001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3f19b8d8bbf0'
down_revision: Union[str, None] = '613a66bc7de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status_register', sa.Enum('PRE_RIGSTER_STATUS', 'START_REGISTER', 'CREATER_CHARACTER', 'SEND_NAME_CHARACTER', 'SELECT_GENDER', 'SELECT_POSITION', 'TERRITORY_ACADEMY', 'JOIN_TO_CLUB', 'FIRST_TRAINING', 'FORGOT_TRAINING', 'END_TRAINING', name='status_user_register'), server_default=sa.text("'END_TRAINING'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status_register')
    # ### end Alembic commands ###
