"""add_new_table_duel

Revision ID: 42ea2fcf925e
Revises: 5706316bd271
Create Date: 2024-10-13 02:05:49.418829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42ea2fcf925e'
down_revision: Union[str, None] = '5706316bd271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duels',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_1_id', sa.BigInteger(), nullable=True),
    sa.Column('user_2_id', sa.BigInteger(), nullable=True),
    sa.Column('point_user_1', sa.Integer(), server_default='0', nullable=False),
    sa.Column('point_user_2', sa.Integer(), server_default='0', nullable=False),
    sa.Column('bit_user_1', sa.Integer(), server_default='0', nullable=False),
    sa.Column('bit_user_2', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user_1_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['user_2_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duels_id'), 'duels', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_duels_id'), table_name='duels')
    op.drop_table('duels')
    # ### end Alembic commands ###
