"""Добавление новых полей к таблице characters

Revision ID: 497958f560dd
Revises: 47a4e37fb2e8
Create Date: 2024-08-12 12:33:01.265760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '497958f560dd'
down_revision: Union[str, None] = '47a4e37fb2e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('technique', sa.Integer(), nullable=True))
    op.add_column('characters', sa.Column('kicks', sa.Integer(), nullable=True))
    op.add_column('characters', sa.Column('ball_selection', sa.Integer(), nullable=True))
    op.add_column('characters', sa.Column('endurance', sa.Integer(), nullable=True))
    op.add_column('characters', sa.Column('gender', sa.String(length=255), nullable=True))
    op.drop_column('characters', 'impact_force')
    op.drop_column('characters', 'energy')
    op.drop_column('characters', 'ball_game')
    op.drop_column('characters', 'tactics')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('tactics', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('characters', sa.Column('ball_game', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('characters', sa.Column('energy', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('characters', sa.Column('impact_force', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('characters', 'gender')
    op.drop_column('characters', 'endurance')
    op.drop_column('characters', 'ball_selection')
    op.drop_column('characters', 'kicks')
    op.drop_column('characters', 'technique')
    # ### end Alembic commands ###
