"""Add club_id to characters

Revision ID: 612432c6a373
Revises: 255aed4ceb1f
Create Date: 2024-08-14 16:15:48.915417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '612432c6a373'
down_revision: Union[str, None] = '255aed4ceb1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('club_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'characters', 'clubs', ['club_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'characters', type_='foreignkey')
    op.drop_column('characters', 'club_id')
    # ### end Alembic commands ###
