"""add new column in characters table

Revision ID: 613a66bc7de0
Revises: 8fc7d4d31a42
Create Date: 2025-02-19 20:22:00.510506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '613a66bc7de0'
down_revision: Union[str, None] = '8fc7d4d31a42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('training_key', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_change_position_payment_id', 'change_position_payment', ['id'], unique=False)
    # ### end Alembic commands ###
