"""add new column

Revision ID: 7448fb71c996
Revises: bfe77d445c0c
Create Date: 2024-12-04 21:52:01.847872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7448fb71c996'
down_revision: Union[str, None] = 'bfe77d445c0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_fight', sa.Column('is_top_20_club', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league_fight', 'is_top_20_club')
    # ### end Alembic commands ###
