"""add_column_money_and_exp_in_character

Revision ID: 78c84de2aac3
Revises: db7e15692607
Create Date: 2024-09-05 00:04:03.849489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '78c84de2aac3'
down_revision: Union[str, None] = 'db7e15692607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('exp', sa.Integer(), server_default='0', nullable=True))
    op.add_column('characters', sa.Column('money', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'money')
    op.drop_column('characters', 'exp')
    # ### end Alembic commands ###
