"""add new_column

Revision ID: 7f6c84aad7d0
Revises: ec258bb7f6eb
Create Date: 2025-04-26 04:29:13.202257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7f6c84aad7d0'
down_revision: Union[str, None] = 'ec258bb7f6eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('characters', sa.Column('time_get_member_bonus', sa.DateTime(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'time_get_member_bonus')
    # ### end Alembic commands ###
