"""add_column_is_fake_club

Revision ID: 812064143a86
Revises: 45489b087ae9
Create Date: 2024-08-21 15:57:07.353910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '812064143a86'
down_revision: Union[str, None] = '45489b087ae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('is_fake_club', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clubs', 'is_fake_club')
    # ### end Alembic commands ###
