"""fix_item

Revision ID: 8492237e9259
Revises: a54f3e3e4036
Create Date: 2024-09-06 17:54:10.493397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8492237e9259'
down_revision: Union[str, None] = 'a54f3e3e4036'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.Enum('T_SHIRT', 'SHORTS', 'GAITERS', 'BOOTS', name='itemcategory'), nullable=True),
    sa.Column('level_required', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('stats', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=False)
    op.add_column('characters', sa.Column('t_shirt_id', sa.BigInteger(), nullable=True))
    op.add_column('characters', sa.Column('shorts_id', sa.BigInteger(), nullable=True))
    op.add_column('characters', sa.Column('gaiters_id', sa.BigInteger(), nullable=True))
    op.add_column('characters', sa.Column('boots_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key('fk_characters_t_shirt', 'characters', 'items', ['t_shirt_id'], ['id'])
    op.create_foreign_key('fk_characters_shorts', 'characters', 'items', ['shorts_id'], ['id'])
    op.create_foreign_key('fk_characters_gaiters', 'characters', 'items', ['gaiters_id'], ['id'])
    op.create_foreign_key('fk_characters_boots', 'characters', 'items', ['boots_id'], ['id'])
    op.alter_column('clubs', 'league',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=254),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clubs', 'league',
               existing_type=sa.String(length=254),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_constraint("fk_characters_t_shirt", 'characters', type_='foreignkey')
    op.drop_constraint("fk_characters_shorts", 'characters', type_='foreignkey')
    op.drop_constraint("fk_characters_gaiters", 'characters', type_='foreignkey')
    op.drop_constraint("fk_characters_boots", 'characters', type_='foreignkey')
    op.drop_column('characters', 'boots_id')
    op.drop_column('characters', 'gaiters_id')
    op.drop_column('characters', 'shorts_id')
    op.drop_column('characters', 't_shirt_id')
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
