"""update training table| add new column end_training

Revision ID: 8fc7d4d31a42
Revises: 7c3a15e4f698
Create Date: 2025-02-17 19:00:03.325830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8fc7d4d31a42'
down_revision: Union[str, None] = '7c3a15e4f698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('character_join_training', sa.Column('training_is_end', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character_join_training', 'training_is_end')
    # ### end Alembic commands ###
