"""rename_last_education_reward_date_to_education_reward_date

Revision ID: a54f3e3e4036
Revises: 21ca36d4d346
Create Date: 2024-09-05 00:57:25.575145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a54f3e3e4036'
down_revision: Union[str, None] = '21ca36d4d346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('education_reward_date', sa.DateTime(), server_default=sa.text("'1970-01-01 00:00:00'"), nullable=True))
    op.drop_column('characters', 'last_reward_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('last_reward_date', mysql.DATETIME(), server_default=sa.text("'1970-01-01 00:00:00'"), nullable=True))
    op.drop_column('characters', 'education_reward_date')
    # ### end Alembic commands ###
