"""add_new_column_schema_in_table_clubs

Revision ID: ab7f83f56211
Revises: b831d7154ec9
Create Date: 2024-10-01 15:16:00.790907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab7f83f56211'
down_revision: Union[str, None] = 'b831d7154ec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('schema', sa.String(length=255), server_default='sсhema_1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clubs', 'schema')
    # ### end Alembic commands ###
