"""add_new_from_character_column_time_add_to_club

Revision ID: b315aefd092f
Revises: b3f279f03ea1
Create Date: 2024-09-13 12:39:26.318339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b315aefd092f'
down_revision: Union[str, None] = 'b3f279f03ea1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('time_to_join_club', sa.DateTime(), server_default=sa.text("'1970-01-01 00:00:00'"), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'time_to_join_club')
    # ### end Alembic commands ###
