"""add training

Revision ID: b326b2b87578
Revises: 00418a0286f0
Create Date: 2025-02-16 11:29:14.230473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b326b2b87578'
down_revision: Union[str, None] = '00418a0286f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_timer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_start', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_timer_id'), 'training_timer', ['id'], unique=False)
    op.create_table('character_join_training',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('character_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('time_join', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('scores', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_join_training_id'), 'character_join_training', ['id'], unique=False)
    op.drop_index('ix_change_position_payment_id', table_name='change_position_payment')
    op.drop_table('change_position_payment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_position_payment',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('order_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('position', mysql.ENUM('MIDFIELDER', 'DEFENDER', 'GOALKEEPER', 'ATTACKER'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['payments.order_id'], name='change_position_payment_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_change_position_payment_id', 'change_position_payment', ['id'], unique=False)
    op.drop_index(op.f('ix_character_join_training_id'), table_name='character_join_training')
    op.drop_table('character_join_training')
    op.drop_index(op.f('ix_training_timer_id'), table_name='training_timer')
    op.drop_table('training_timer')
    # ### end Alembic commands ###
