"""add_new_column_referal_user_id_in_user_bot

Revision ID: bb602897c1e5
Revises: fe9336d4c9fd
Create Date: 2024-10-10 15:08:32.209526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb602897c1e5'
down_revision: Union[str, None] = 'fe9336d4c9fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referal_user_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'referal_user_id')
    # ### end Alembic commands ###
