"""edit column league fight

Revision ID: bfe77d445c0c
Revises: a34028cb8757
Create Date: 2024-11-23 17:50:18.174959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfe77d445c0c'
down_revision: Union[str, None] = 'a34028cb8757'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_fight', sa.Column('is_beast_league', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league_fight', 'is_beast_league')
    # ### end Alembic commands ###
