"""add_new_column_referal_award_is_received_in_table_characters

Revision ID: caa31690c864
Revises: bb602897c1e5
Create Date: 2024-10-10 18:31:17.359051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caa31690c864'
down_revision: Union[str, None] = 'bb602897c1e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('referral_award_is_received', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'referral_award_is_received')
    # ### end Alembic commands ###
