"""add_column_is_bot_character

Revision ID: d8be20e40ed0
Revises: 255cc8c925bf
Create Date: 2024-08-21 14:06:59.143200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8be20e40ed0'
down_revision: Union[str, None] = '255cc8c925bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('is_bot', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'is_bot')
    # ### end Alembic commands ###
