"""add_column_group_id

Revision ID: db7e15692607
Revises: b9690291c7d0
Create Date: 2024-08-23 18:23:42.790926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db7e15692607'
down_revision: Union[str, None] = 'b9690291c7d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_fight', sa.Column('group_id', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league_fight', 'group_id')
    # ### end Alembic commands ###
