"""add_new_column_reiting

Revision ID: f8ee34ff5fd5
Revises: 612432c6a373
Create Date: 2024-08-14 19:54:16.695320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f8ee34ff5fd5'
down_revision: Union[str, None] = '612432c6a373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('reiting', sa.Integer(), nullable=True))
    op.drop_column('clubs', 'league')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('league', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('clubs', 'reiting')
    # ### end Alembic commands ###
