"""New column current_energy

Revision ID: f8fd066f807d
Revises: 614f1742042e
Create Date: 2024-08-12 16:21:56.442261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8fd066f807d'
down_revision: Union[str, None] = '614f1742042e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('current_energy', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'current_energy')
    # ### end Alembic commands ###
