"""add_new_column_referal_user_id

Revision ID: fe9336d4c9fd
Revises: bf4444fb896d
Create Date: 2024-10-10 14:29:40.832236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe9336d4c9fd'
down_revision: Union[str, None] = 'bf4444fb896d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('referal_user_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'referal_user_id')
    # ### end Alembic commands ###
